// flow-typed signature: 40ad2d31df786b8bd9de83a07a1f17b1
// flow-typed version: <<STUB>>/fortnite.js_v^1.3.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fortnite.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fortnite.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fortnite.js/docs/example' {
  declare module.exports: any;
}

declare module 'fortnite.js/src/Account' {
  declare module.exports: any;
}

declare module 'fortnite.js/src/Client' {
  declare module.exports: any;
}

declare module 'fortnite.js/src/index' {
  declare module.exports: any;
}

declare module 'fortnite.js/src/Match' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fortnite.js/docs/example.js' {
  declare module.exports: $Exports<'fortnite.js/docs/example'>;
}
declare module 'fortnite.js/src/Account.js' {
  declare module.exports: $Exports<'fortnite.js/src/Account'>;
}
declare module 'fortnite.js/src/Client.js' {
  declare module.exports: $Exports<'fortnite.js/src/Client'>;
}
declare module 'fortnite.js/src/index.js' {
  declare module.exports: $Exports<'fortnite.js/src/index'>;
}
declare module 'fortnite.js/src/Match.js' {
  declare module.exports: $Exports<'fortnite.js/src/Match'>;
}
